### PR TITLE
feat(charts/strichlistensystem): add chart, feat(charts/portals): add new env vars

### LINKED ISSUE #15: add chart for "strichlistensystem"

### PR DESCRIPTION
**Pull request by simonostendorf**
Closes #15

### CODE REVIEW

**Comment by simonostendorf** [comment]
Wait for https://github.com/fsr5-fhaachen/strichlistensystem/issues/29 to implement the new importer and include the needed files in the seed-job here.

**Comment by simonostendorf** [comment]
Remember to add VPN

**Comment by simonostendorf** [comment]
> Remember to add VPN

See https://github.com/fsr5-fhaachen/strichlistensystem/pull/76

**Comment by simonostendorf** [comment]
Adjust env vars:
```
APP_VPN_IP (remove)
APP_IS_VPN=false
APP_PORTALS_URL=http://127.0.0.1:8000
APP_PORTALS_API_SECRET=secret
APP_PORTALS_IMPORT_PW=123
```

**Review by TitusKirch — DISMISSED** [review]

**Pull request merged**
